version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    container_name: fastapi-backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:8000"
    container_name: react-frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge